---
Name: trademeroutes
---
SilverStripe\Control\Director:
  rules:
    admin/set-trade-me-categories//$Action/$ID/$OtherID: Sunnysideup\EcommerceTrademe\Control\TradeMeAssignGroupController
    admin/set-trade-me-products//$Action/$ID/$OtherID: Sunnysideup\EcommerceTrademe\Control\TradeMeAssignProductController
